"use client";

import { CheckCircle2, Clock3, MapPin, Pencil, Plus, Trash2, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";

import { closeLiveAttendance, createHistoricalAttendance, deleteAttendanceActivity, saveAttendanceActivity, startLiveAttendance } from "@/app/(consultant)/consultant/attendance-actions";
import { ATTENDANCE_AREAS, getAttendanceAreaLabel } from "@/lib/attendance/areas";
import { calculateHoursBetween, declaredHoursToMinutes, formatDeclaredMinutes, normalizeDeclaredHours } from "@/lib/attendance/hours";
import { formatLimaDate } from "@/lib/attendance/lima";

type Client = { id: string; name: string };
type Activity = { id: string; areaCode: string; otherAreaName: string | null; description: string };
export type OpenAttendance = { id: string; workDate: string; clientName: string; entryTime: string; activities: Activity[] };
type LocationData = { status: string; latitude: number | null; longitude: number | null; accuracy: number | null };
type View = "start" | "confirm-start" | "activity" | "close" | "confirm-close" | "success" | null;
type Draft = { clientId: string; workDate: string; workType: "remote" | "onsite" | ""; entryTime: string; exitTime: string; declaredHours: string; areaCode: string; otherAreaName: string; description: string };
const timePattern = /^([01]\d|2[0-3]):[0-5]\d$/;
const emptyLocation: LocationData = { status: "unsupported", latitude: null, longitude: null, accuracy: null };

function todayInLima() { const p = new Intl.DateTimeFormat("en", { timeZone: "America/Lima", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date()); const v = (t: Intl.DateTimeFormatPartTypes) => p.find((x) => x.type === t)?.value ?? ""; return `${v("year")}-${v("month")}-${v("day")}`; }
function addLocation(data: FormData, location: LocationData) { data.set("locationStatus", location.status); if (location.latitude !== null) data.set("latitude", String(location.latitude)); if (location.longitude !== null) data.set("longitude", String(location.longitude)); if (location.accuracy !== null) data.set("accuracy", String(location.accuracy)); }
async function captureLocation(): Promise<LocationData> { if (!navigator.geolocation) return emptyLocation; return new Promise((resolve) => navigator.geolocation.getCurrentPosition((p) => resolve({ status: "granted", latitude: p.coords.latitude, longitude: p.coords.longitude, accuracy: p.coords.accuracy }), (e) => resolve({ status: e.code === e.PERMISSION_DENIED ? "permission_denied" : e.code === e.TIMEOUT ? "timeout" : "position_unavailable", latitude: null, longitude: null, accuracy: null }), { enableHighAccuracy: true, timeout: 10000, maximumAge: 0 })); }

export function AttendanceAction({ assignedClients, openAttendance }: { assignedClients: Client[]; openAttendance: OpenAttendance | null }) {
  const router = useRouter(); const today = todayInLima();
  const [view, setView] = useState<View>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [editing, setEditing] = useState<Activity | null>(null); const [successDate, setSuccessDate] = useState<string | null>(null);
  const [historicalHoursManual, setHistoricalHoursManual] = useState(false);
  const [draft, setDraft] = useState<Draft>({ clientId: assignedClients[0]?.id ?? "", workDate: today, workType: "", entryTime: "", exitTime: "", declaredHours: "", areaCode: "", otherAreaName: "", description: "" });
  const historical = draft.workDate < today;
  const change = (next: Partial<Draft>) => setDraft((current) => ({ ...current, ...next }));
  const effectiveDeclaredHours = historical && !historicalHoursManual
    ? calculateHoursBetween(draft.entryTime, draft.exitTime)
    : normalizeDeclaredHours(draft.declaredHours);

  function begin() { setError(null); setHistoricalHoursManual(false); if (!assignedClients.length) { setError("Aún no tienes un cliente activo asignado. Solicita la asignación a administración."); return; } setDraft({ clientId: assignedClients[0]?.id ?? "", workDate: today, workType: "", entryTime: "", exitTime: "", declaredHours: "", areaCode: "", otherAreaName: "", description: "" }); setView("start"); }
  function validateStart() { if (!draft.clientId || !draft.workDate || !draft.workType || !timePattern.test(draft.entryTime)) return "Completa la fecha, tipo de jornada, cliente y hora de ingreso."; if (draft.workDate > today) return "La fecha de asistencia no puede ser futura."; if (!historical) return null; if (!timePattern.test(draft.exitTime) || !declaredHoursToMinutes(effectiveDeclaredHours) || !draft.areaCode || !draft.description.trim()) return "Completa la salida, horas declaradas y actividad de la jornada anterior."; if (draft.exitTime < draft.entryTime) return "La hora de salida debe ser igual o posterior a la de ingreso."; if (draft.areaCode === "other" && !draft.otherAreaName.trim()) return "Indica el área específica."; change({ declaredHours: effectiveDeclaredHours }); return null; }
  async function submitStart() { setBusy(true); setError(null); const data = new FormData(); for (const [key, value] of Object.entries({ clientId: draft.clientId, workDate: draft.workDate, workType: draft.workType, entryTime: draft.entryTime, exitTime: draft.exitTime, declaredHours: effectiveDeclaredHours, areaCode: draft.areaCode, otherAreaName: draft.otherAreaName, description: draft.description })) data.set(key, value); addLocation(data, await captureLocation()); const result = historical ? await createHistoricalAttendance(data) : await startLiveAttendance(data); setBusy(false); if (!result.success) { setError(result.error); setView("start"); return; } if (historical) { setSuccessDate(draft.workDate); setView("success"); } else setView(null); router.refresh(); }
  async function submitActivity(data: FormData) { if (!openAttendance) return; setBusy(true); setError(null); data.set("sessionId", openAttendance.id); if (editing) data.set("activityId", editing.id); const result = await saveAttendanceActivity(data); setBusy(false); if (!result.success) { setError(result.error); return; } setEditing(null); setView(null); router.refresh(); }
  async function deleteActivity(activity: Activity) { if (!openAttendance || !window.confirm("¿Deseas eliminar esta actividad de la jornada abierta?")) return; setBusy(true); const result = await deleteAttendanceActivity(activity.id, openAttendance.id); setBusy(false); if (!result.success) { setError(result.error); return; } router.refresh(); }
  async function submitClose() { if (!openAttendance) return; setBusy(true); const data = new FormData(); data.set("sessionId", openAttendance.id); data.set("exitTime", draft.exitTime); data.set("declaredHours", normalizeDeclaredHours(draft.declaredHours)); addLocation(data, await captureLocation()); const result = await closeLiveAttendance(data); setBusy(false); if (!result.success) { setError(result.error); setView("close"); return; } setSuccessDate(openAttendance.workDate); setView("success"); router.refresh(); }
  const pending = !!openAttendance && openAttendance.workDate !== today;
  const minutes = declaredHoursToMinutes(effectiveDeclaredHours) ?? 0;

  return <>
    {openAttendance ? <OpenCard attendance={openAttendance} busy={busy} error={error} pending={pending} onActivity={() => { setError(null); setEditing(null); setView("activity"); }} onEdit={(a) => { setError(null); setEditing(a); setView("activity"); }} onDelete={deleteActivity} onClose={() => { setError(null); setView("close"); }} /> : <div className="xl:w-[430px]"><button className="flex min-h-[78px] w-full items-center justify-center gap-4 rounded-[15px] bg-[linear-gradient(135deg,#a9bf00_0%,#bad100_55%,#a9c000_100%)] px-7 text-lg font-semibold text-white shadow-[0_14px_30px_rgba(154,177,0,0.18)]" onClick={begin} type="button"><Clock3 className="size-9" />Registrar asistencia</button>{error ? <p className="mt-3 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p> : null}</div>}
    {view === "start" ? <StartDialog clients={assignedClients} draft={draft} today={today} historical={historical} historicalHoursManual={historicalHoursManual} calculatedHours={calculateHoursBetween(draft.entryTime, draft.exitTime)} error={error} change={change} setHistoricalHoursManual={setHistoricalHoursManual} cancel={() => setView(null)} continue={() => { const message = validateStart(); if (message) { setError(message); return; } setError(null); setView("confirm-start"); }} /> : null}
    {view === "confirm-start" ? <Confirm title={historical ? "Confirmar jornada histórica" : "Confirmar inicio de jornada"} description={historical ? `Registrarás la jornada del ${formatLimaDate(draft.workDate)}. Ingreso: ${draft.entryTime}; salida: ${draft.exitTime}; horas declaradas: ${formatDeclaredMinutes(minutes)}.` : `Registrarás tu ingreso de hoy a las ${draft.entryTime}. Esta hora quedará bloqueada para ti.`} confirmLabel={historical ? "Sí, registrar jornada" : "Sí, confirmar ingreso"} busy={busy} cancel={() => setView("start")} confirm={submitStart} /> : null}
    {view === "activity" && openAttendance ? <ActivityDialog activity={editing} busy={busy} error={error} cancel={() => { setEditing(null); setView(null); }} submit={submitActivity} /> : null}
    {view === "close" && openAttendance ? <CloseDialog draft={draft} error={error} activityCount={openAttendance.activities.length} change={change} cancel={() => setView(null)} continue={() => { const normalized = normalizeDeclaredHours(draft.declaredHours); if (!timePattern.test(draft.exitTime) || !declaredHoursToMinutes(normalized)) { setError("Completa una salida y horas declaradas válidas en formato HH:MM."); return; } if (!openAttendance.activities.length) { setError("Registra al menos una actividad antes de marcar la salida."); return; } change({ declaredHours: normalized }); setError(null); setView("confirm-close"); }} /> : null}
    {view === "confirm-close" ? <Confirm title="¿Confirmas el cierre de tu jornada?" description={`Registrarás la salida a las ${draft.exitTime} y ${formatDeclaredMinutes(minutes)} como horas declaradas. Una vez confirmada, la jornada quedará en solo lectura.`} confirmLabel="Sí, continuar" secondary="No, seguir editando" busy={busy} cancel={() => setView("close")} confirm={submitClose} /> : null}
    {view === "success" && successDate ? <Success date={successDate} close={() => { setSuccessDate(null); setView(null); }} /> : null}
  </>;
}

function Modal({ title, children, close }: { title: string; children: React.ReactNode; close: () => void }) { return <div aria-modal="true" className="fixed inset-0 z-50 flex items-center justify-center bg-black/35 p-4 backdrop-blur-[2px]" role="dialog"><section className="relative max-h-[92vh] w-full max-w-lg overflow-y-auto rounded-[22px] bg-white p-6 shadow-[0_28px_80px_rgba(15,23,42,0.25)] sm:p-8"><button aria-label="Cerrar" className="absolute top-4 right-4 p-2 text-[#697186]" onClick={close} type="button"><X /></button><h2 className="pr-10 text-2xl font-bold">{title}</h2>{children}</section></div>; }
function StartDialog({ clients, draft, today, historical, historicalHoursManual, calculatedHours, error, change, setHistoricalHoursManual, cancel, continue: proceed }: { clients: Client[]; draft: Draft; today: string; historical: boolean; historicalHoursManual: boolean; calculatedHours: string; error: string | null; change: (v: Partial<Draft>) => void; setHistoricalHoursManual: (value: boolean) => void; cancel: () => void; continue: () => void }) { return <Modal close={cancel} title={historical ? "Registrar jornada anterior" : "Registrar ingreso"}><p className="mt-2 text-sm text-[#697186]">Selecciona la fecha de asistencia. Las fechas pasadas se registran completas y cerradas.</p><label className="mt-5 block text-sm font-semibold">Fecha de asistencia<input className="consultant-field mt-2" type="date" max={today} value={draft.workDate} onChange={(e) => { setHistoricalHoursManual(false); change({ workDate: e.target.value }); }} /></label><label className="mt-5 block text-sm font-semibold">Tipo de jornada<select className="consultant-field mt-2" value={draft.workType} onChange={(e) => change({ workType: e.target.value as Draft["workType"] })}><option value="" disabled>Selecciona un tipo</option><option value="remote">Remota</option><option value="onsite">Presencial</option></select></label><label className="mt-5 block text-sm font-semibold">Cliente asignado<select className="consultant-field mt-2" value={draft.clientId} onChange={(e) => change({ clientId: e.target.value })}>{clients.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="mt-5 block text-sm font-semibold">Hora de ingreso<input className="consultant-field mt-2" type="time" value={draft.entryTime} onChange={(e) => change({ entryTime: e.target.value })} /></label>{historical ? <HistoricalFields draft={draft} calculatedHours={calculatedHours} change={change} manual={historicalHoursManual} setManual={setHistoricalHoursManual} /> : null}{error ? <p className="mt-4 text-sm text-red-700">{error}</p> : null}<Buttons cancel={cancel} confirm={proceed} label="Continuar" /></Modal>; }
function HistoricalFields({ draft, calculatedHours, change, manual, setManual }: { draft: Draft; calculatedHours: string; change: (v: Partial<Draft>) => void; manual: boolean; setManual: (value: boolean) => void }) { const useManual = () => { change({ declaredHours: calculatedHours }); setManual(true); }; return <div className="mt-5 border-t pt-5"><p className="text-sm font-semibold text-[#52617a]">Datos de la jornada anterior</p><label className="mt-4 block text-sm font-semibold">Hora de salida<input className="consultant-field mt-2" type="time" value={draft.exitTime} onChange={(e) => change({ exitTime: e.target.value })} /></label><label className="mt-5 block text-sm font-semibold">Horas trabajadas declaradas<input className="consultant-field mt-2" inputMode="numeric" placeholder="Completa ingreso y salida" disabled={!manual} value={manual ? draft.declaredHours : calculatedHours} onBlur={() => change({ declaredHours: normalizeDeclaredHours(draft.declaredHours) })} onChange={(e) => change({ declaredHours: e.target.value })} /></label><p className="mt-1 text-xs text-[#697186]">{manual ? "Formato HH:MM. Ejemplo: 6 se normaliza a 06:00." : "Calculadas automáticamente desde ingreso y salida para esta jornada histórica."}</p>{manual ? <button className="mt-3 min-h-10 rounded-lg border border-[#a9c000] px-4 text-sm font-semibold text-[#617300]" onClick={() => setManual(false)} type="button">Usar cálculo automático</button> : <button className="mt-3 min-h-10 rounded-lg border border-[#a9c000] px-4 text-sm font-semibold text-[#617300]" onClick={useManual} type="button">Colocar manualmente las horas</button>}<label className="mt-5 block text-sm font-semibold">Área<select className="consultant-field mt-2" value={draft.areaCode} onChange={(e) => change({ areaCode: e.target.value })}><option value="" disabled>Selecciona un área</option>{ATTENDANCE_AREAS.map((a) => <option key={a.code} value={a.code}>{a.label}</option>)}</select></label>{draft.areaCode === "other" ? <label className="mt-5 block text-sm font-semibold">Área específica<input className="consultant-field mt-2" maxLength={120} value={draft.otherAreaName} onChange={(e) => change({ otherAreaName: e.target.value })} /></label> : null}<label className="mt-5 block text-sm font-semibold">Motivo o concepto de la reunión<textarea className="consultant-field mt-2 min-h-28" maxLength={250} value={draft.description} onChange={(e) => change({ description: e.target.value })} /></label></div>; }
function ActivityDialog({ activity, busy, error, cancel, submit }: { activity: Activity | null; busy: boolean; error: string | null; cancel: () => void; submit: (d: FormData) => void }) { const [area, setArea] = useState(activity?.areaCode ?? ""); return <Modal close={cancel} title={activity ? "Editar actividad" : "Registrar actividad"}><form action={submit} className="mt-6"><label className="block text-sm font-semibold">Área<select className="consultant-field mt-2" name="areaCode" required value={area} onChange={(e) => setArea(e.target.value)}><option value="" disabled>Selecciona un área</option>{ATTENDANCE_AREAS.map((a) => <option key={a.code} value={a.code}>{a.label}</option>)}</select></label>{area === "other" ? <label className="mt-5 block text-sm font-semibold">Área específica<input className="consultant-field mt-2" defaultValue={activity?.otherAreaName ?? ""} name="otherAreaName" required /></label> : null}<label className="mt-5 block text-sm font-semibold">Motivo o concepto de la reunión<textarea className="consultant-field mt-2 min-h-28" defaultValue={activity?.description ?? ""} name="description" required /></label>{error ? <p className="mt-4 text-sm text-red-700">{error}</p> : null}<Buttons cancel={cancel} busy={busy} label="Guardar actividad" /></form></Modal>; }
function CloseDialog({ draft, error, activityCount, change, cancel, continue: proceed }: { draft: Draft; error: string | null; activityCount: number; change: (v: Partial<Draft>) => void; cancel: () => void; continue: () => void }) { return <Modal close={cancel} title="Registrar salida"><p className="mt-2 text-sm text-[#697186]">Confirma la salida y escribe las horas que realmente deben computarse. No se calculan desde el ingreso y la salida.</p><label className="mt-5 block text-sm font-semibold">Hora de salida<input className="consultant-field mt-2" type="time" value={draft.exitTime} onChange={(e) => change({ exitTime: e.target.value })} /></label><label className="mt-5 block text-sm font-semibold">Horas trabajadas declaradas<input className="consultant-field mt-2" inputMode="numeric" placeholder="Ej. 08:00" value={draft.declaredHours} onBlur={() => change({ declaredHours: normalizeDeclaredHours(draft.declaredHours) })} onChange={(e) => change({ declaredHours: e.target.value })} /></label><p className="mt-1 text-xs text-[#697186]">Formato HH:MM. Ejemplo: 6 se normaliza a 06:00.</p>{activityCount === 0 ? <p className="mt-4 text-sm text-red-700">Debes registrar al menos una actividad antes de cerrar.</p> : null}{error ? <p className="mt-4 text-sm text-red-700">{error}</p> : null}<Buttons cancel={cancel} confirm={proceed} label="Marcar asistencia" /></Modal>; }
function Confirm({ title, description, confirmLabel, secondary = "Cancelar", busy, cancel, confirm }: { title: string; description: string; confirmLabel: string; secondary?: string; busy: boolean; cancel: () => void; confirm: () => void }) { return <Modal close={cancel} title={title}><div className="mt-5 flex gap-3 rounded-2xl bg-[#f4f7e9] p-4"><MapPin className="size-5 text-[#6c8500]" /><p className="text-sm text-[#394458]">{description}</p></div><p className="mt-4 text-sm text-[#697186]">La ubicación se solicitará ahora; si no está disponible, el registro continuará con la incidencia correspondiente.</p><Buttons cancel={cancel} confirm={confirm} busy={busy} cancelLabel={secondary} label={confirmLabel} /></Modal>; }
function Success({ date, close }: { date: string; close: () => void }) { return <Modal close={close} title="Asistencia marcada"><div className="mt-6 text-center"><CheckCircle2 className="mx-auto size-16 text-[#758f00]" /><p className="mt-5 text-lg font-semibold">Tu asistencia del {formatLimaDate(date)} fue marcada correctamente.</p><p className="mt-2 text-[#697186]">Gracias por registrar tu jornada.</p><button className="mt-7 min-h-11 rounded-xl bg-[#afc500] px-7 font-semibold text-white" onClick={close}>Entendido</button></div></Modal>; }
function Buttons({ cancel, confirm, label, busy = false, cancelLabel = "Cancelar" }: { cancel: () => void; confirm?: () => void; label: string; busy?: boolean; cancelLabel?: string }) { return <div className="mt-7 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button className="min-h-11 rounded-xl border border-[#d7dce4] px-5 font-semibold" type="button" onClick={cancel}>{cancelLabel}</button><button className="min-h-11 rounded-xl bg-[#afc500] px-5 font-semibold text-white disabled:opacity-60" type={confirm ? "button" : "submit"} disabled={busy} onClick={confirm}>{busy ? "Registrando..." : label}</button></div>; }
function OpenCard({ attendance, pending, busy, error, onActivity, onEdit, onDelete, onClose }: { attendance: OpenAttendance; pending: boolean; busy: boolean; error: string | null; onActivity: () => void; onEdit: (a: Activity) => void; onDelete: (a: Activity) => void; onClose: () => void }) { return <div className="w-full xl:w-[500px]">{pending ? <div className="mb-3 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-medium text-red-800">Tienes una jornada pendiente del {formatLimaDate(attendance.workDate)}. Debes marcar su salida antes de iniciar una nueva.</div> : null}<div className="rounded-[18px] border border-[#e8ebef] bg-white p-5 shadow-[0_12px_35px_rgba(15,23,42,0.06)]"><p className="text-sm font-semibold text-[#68758b]">Jornada abierta · {attendance.clientName}</p><p className="mt-1 text-xl font-bold">Ingreso: {attendance.entryTime}</p><div className="mt-4 space-y-2">{attendance.activities.map((a) => <div className="flex items-start justify-between gap-3 rounded-xl bg-[#f7f8fa] px-3 py-2" key={a.id}><p className="text-sm"><strong>{a.areaCode === "other" ? a.otherAreaName : getAttendanceAreaLabel(a.areaCode)}:</strong> {a.description}</p><span className="flex"><button aria-label="Editar actividad" onClick={() => onEdit(a)}><Pencil className="size-4" /></button><button aria-label="Eliminar actividad" disabled={busy} className="ml-2 text-red-600" onClick={() => onDelete(a)}><Trash2 className="size-4" /></button></span></div>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-2"><button className="min-h-11 rounded-xl border border-[#cfd6df] px-4 font-semibold" onClick={onActivity}><Plus className="mr-1 inline size-4" />Actividad</button><button className="min-h-11 rounded-xl bg-[#afc500] px-4 font-semibold text-white disabled:opacity-60" disabled={busy || !attendance.activities.length} onClick={onClose}>Registrar salida</button></div>{!attendance.activities.length ? <p className="mt-3 text-xs text-[#697186]">Registra al menos una actividad para habilitar la salida.</p> : null}{error ? <p className="mt-3 text-sm text-red-700">{error}</p> : null}</div></div>; }
