"use client";

import { CheckCircle2, Clock3, MapPin, Pencil, Plus, Trash2, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";

import { closeLiveAttendance, createHistoricalAttendance, deleteAttendanceActivity, saveAttendanceActivity, startLiveAttendance } from "@/app/(consultant)/consultant/attendance-actions";
import { ATTENDANCE_AREAS, getAttendanceAreaLabel } from "@/lib/attendance/areas";
import { calculateHoursBetween, declaredHoursToMinutes, formatDeclaredMinutes, normalizeDeclaredHours } from "@/lib/attendance/hours";
import { formatLimaDate } from "@/lib/attendance/lima";

type Client = { id: string; name: string };
type Activity = { id: string; areaCode: string; otherAreaName: string | null; description: string };
type HistoricalActivity = { id: string; areaCode: string; otherAreaName: string; description: string };
export type OpenAttendance = { id: string; workDate: string; clientName: string; entryTime: string; activities: Activity[] };
type LocationData = { status: string; latitude: number | null; longitude: number | null; accuracy: number | null };
type View = "start" | "confirm-start" | "activity" | "close" | "confirm-close" | "success" | null;
type Draft = { clientId: string; workDate: string; workType: "remote" | "onsite" | ""; entryTime: string; exitTime: string; declaredHours: string };

const timePattern = /^([01]\d|2[0-3]):[0-5]\d$/;
const emptyLocation: LocationData = { status: "unsupported", latitude: null, longitude: null, accuracy: null };
const blankHistoricalActivity = (): HistoricalActivity => ({ id: crypto.randomUUID(), areaCode: "", otherAreaName: "", description: "" });

function todayInLima() {
  const parts = new Intl.DateTimeFormat("en", { timeZone: "America/Lima", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date());
  const part = (type: Intl.DateTimeFormatPartTypes) => parts.find((item) => item.type === type)?.value ?? "";
  return `${part("year")}-${part("month")}-${part("day")}`;
}

function addLocation(data: FormData, location: LocationData) {
  data.set("locationStatus", location.status);
  if (location.latitude !== null) data.set("latitude", String(location.latitude));
  if (location.longitude !== null) data.set("longitude", String(location.longitude));
  if (location.accuracy !== null) data.set("accuracy", String(location.accuracy));
}

async function captureLocation(): Promise<LocationData> {
  if (!navigator.geolocation) return emptyLocation;
  return new Promise((resolve) => navigator.geolocation.getCurrentPosition(
    (position) => resolve({ status: "granted", latitude: position.coords.latitude, longitude: position.coords.longitude, accuracy: position.coords.accuracy }),
    (error) => resolve({ status: error.code === error.PERMISSION_DENIED ? "permission_denied" : error.code === error.TIMEOUT ? "timeout" : "position_unavailable", latitude: null, longitude: null, accuracy: null }),
    { enableHighAccuracy: true, timeout: 10000, maximumAge: 0 },
  ));
}

export function AttendanceAction({ assignedClients, openAttendance }: { assignedClients: Client[]; openAttendance: OpenAttendance | null }) {
  const router = useRouter(); const today = todayInLima();
  const [view, setView] = useState<View>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const [editing, setEditing] = useState<Activity | null>(null); const [successDate, setSuccessDate] = useState<string | null>(null);
  const [historicalHoursManual, setHistoricalHoursManual] = useState(false); const [closeHoursManual, setCloseHoursManual] = useState(false);
  const [historicalActivities, setHistoricalActivities] = useState<HistoricalActivity[]>([blankHistoricalActivity()]);
  const [draft, setDraft] = useState<Draft>({ clientId: assignedClients[0]?.id ?? "", workDate: today, workType: "", entryTime: "", exitTime: "", declaredHours: "" });
  const historical = draft.workDate < today;
  const change = (next: Partial<Draft>) => setDraft((current) => ({ ...current, ...next }));
  const calculatedHistoricalHours = calculateHoursBetween(draft.entryTime, draft.exitTime);
  const effectiveHistoricalHours = historicalHoursManual ? normalizeDeclaredHours(draft.declaredHours) : calculatedHistoricalHours;
  const calculatedCloseHours = calculateHoursBetween(openAttendance?.entryTime ?? "", draft.exitTime);
  const effectiveCloseHours = closeHoursManual ? normalizeDeclaredHours(draft.declaredHours) : calculatedCloseHours;

  function begin() {
    setError(null); setHistoricalHoursManual(false); setCloseHoursManual(false); setHistoricalActivities([blankHistoricalActivity()]);
    if (!assignedClients.length) { setError("Aún no tienes un cliente activo asignado. Solicita la asignación a administración."); return; }
    setDraft({ clientId: assignedClients[0]?.id ?? "", workDate: today, workType: "", entryTime: "", exitTime: "", declaredHours: "" }); setView("start");
  }
  function updateHistoricalActivity(id: string, next: Partial<HistoricalActivity>) { setHistoricalActivities((items) => items.map((item) => item.id === id ? { ...item, ...next } : item)); }
  function validateStart() {
    if (!draft.clientId || !draft.workDate || !draft.workType || !timePattern.test(draft.entryTime)) return "Completa la fecha, tipo de jornada, cliente y hora de ingreso.";
    if (draft.workDate > today) return "La fecha de asistencia no puede ser futura.";
    if (!historical) return null;
    if (!timePattern.test(draft.exitTime) || !declaredHoursToMinutes(effectiveHistoricalHours)) return "Completa la salida y las horas declaradas de la jornada anterior.";
    if (draft.exitTime < draft.entryTime) return "La hora de salida debe ser igual o posterior a la de ingreso.";
    if (historicalActivities.some((item) => !item.areaCode || !item.description.trim() || (item.areaCode === "other" && !item.otherAreaName.trim()))) return "Completa el área y motivo de cada actividad de la jornada anterior.";
    change({ declaredHours: effectiveHistoricalHours }); return null;
  }
  async function submitStart() {
    setBusy(true); setError(null); const data = new FormData();
    for (const [key, value] of Object.entries({ clientId: draft.clientId, workDate: draft.workDate, workType: draft.workType, entryTime: draft.entryTime, exitTime: draft.exitTime, declaredHours: effectiveHistoricalHours })) data.set(key, value);
    data.set("activities", JSON.stringify(historicalActivities.map((activity) => ({ areaCode: activity.areaCode, otherAreaName: activity.otherAreaName, description: activity.description })))); addLocation(data, await captureLocation());
    const result = historical ? await createHistoricalAttendance(data) : await startLiveAttendance(data); setBusy(false);
    if (!result.success) { setError(result.error); setView("start"); return; }
    if (historical) { setSuccessDate(draft.workDate); setView("success"); } else setView(null); router.refresh();
  }
  async function submitActivity(data: FormData) {
    if (!openAttendance) return; setBusy(true); setError(null); data.set("sessionId", openAttendance.id); if (editing) data.set("activityId", editing.id);
    const result = await saveAttendanceActivity(data); setBusy(false); if (!result.success) { setError(result.error); return; }
    setEditing(null); setView(null); router.refresh();
  }
  async function deleteActivity(activity: Activity) {
    if (!openAttendance || !window.confirm("¿Deseas eliminar esta actividad de la jornada abierta?")) return; setBusy(true);
    const result = await deleteAttendanceActivity(activity.id, openAttendance.id); setBusy(false); if (!result.success) { setError(result.error); return; } router.refresh();
  }
  async function submitClose() {
    if (!openAttendance) return; setBusy(true); const data = new FormData(); data.set("sessionId", openAttendance.id); data.set("exitTime", draft.exitTime); data.set("declaredHours", effectiveCloseHours); addLocation(data, await captureLocation());
    const result = await closeLiveAttendance(data); setBusy(false); if (!result.success) { setError(result.error); setView("close"); return; }
    setSuccessDate(openAttendance.workDate); setView("success"); router.refresh();
  }
  const pending = !!openAttendance && openAttendance.workDate !== today;
  const confirmationMinutes = declaredHoursToMinutes(historical ? effectiveHistoricalHours : effectiveCloseHours) ?? 0;

  return <>
    {openAttendance ? <OpenCard attendance={openAttendance} busy={busy} error={error} pending={pending} onActivity={() => { setError(null); setEditing(null); setView("activity"); }} onEdit={(activity) => { setError(null); setEditing(activity); setView("activity"); }} onDelete={deleteActivity} onClose={() => { setError(null); setCloseHoursManual(false); change({ exitTime: "", declaredHours: "" }); setView("close"); }} /> : <div className="xl:w-[430px]"><button className="flex min-h-[78px] w-full items-center justify-center gap-4 rounded-[15px] bg-[linear-gradient(135deg,#a9bf00_0%,#bad100_55%,#a9c000_100%)] px-7 text-lg font-semibold text-white shadow-[0_14px_30px_rgba(154,177,0,0.18)]" onClick={begin} type="button"><Clock3 className="size-9" />Registrar asistencia</button>{error ? <p className="mt-3 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p> : null}</div>}
    {view === "start" ? <StartDialog clients={assignedClients} draft={draft} today={today} historical={historical} manual={historicalHoursManual} calculatedHours={calculatedHistoricalHours} activities={historicalActivities} error={error} change={change} updateActivity={updateHistoricalActivity} addActivity={() => setHistoricalActivities((items) => [...items, blankHistoricalActivity()])} removeActivity={(id) => setHistoricalActivities((items) => items.length > 1 ? items.filter((item) => item.id !== id) : items)} setManual={setHistoricalHoursManual} cancel={() => setView(null)} proceed={() => { const message = validateStart(); if (message) { setError(message); return; } setError(null); setView("confirm-start"); }} /> : null}
    {view === "confirm-start" ? <Confirm title={historical ? "Confirmar jornada histórica" : "Confirmar inicio de jornada"} description={historical ? `Registrarás la jornada del ${formatLimaDate(draft.workDate)}. Ingreso: ${draft.entryTime}; salida: ${draft.exitTime}; horas declaradas: ${formatDeclaredMinutes(confirmationMinutes)}.` : `Registrarás tu ingreso de hoy a las ${draft.entryTime}. Esta hora quedará bloqueada para ti.`} confirmLabel={historical ? "Sí, registrar jornada" : "Sí, confirmar ingreso"} busy={busy} cancel={() => setView("start")} confirm={submitStart} /> : null}
    {view === "activity" && openAttendance ? <ActivityDialog activity={editing} busy={busy} error={error} cancel={() => { setEditing(null); setView(null); }} submit={submitActivity} /> : null}
    {view === "close" && openAttendance ? <CloseDialog draft={draft} calculatedHours={calculatedCloseHours} manual={closeHoursManual} setManual={setCloseHoursManual} error={error} activityCount={openAttendance.activities.length} change={change} cancel={() => setView(null)} proceed={() => { if (!timePattern.test(draft.exitTime) || !declaredHoursToMinutes(effectiveCloseHours)) { setError("Completa una salida y horas declaradas válidas en formato HH:MM."); return; } if (!openAttendance.activities.length) { setError("Registra al menos una actividad antes de marcar la salida."); return; } change({ declaredHours: effectiveCloseHours }); setError(null); setView("confirm-close"); }} /> : null}
    {view === "confirm-close" ? <Confirm title="¿Confirmas el cierre de tu jornada?" description={`Registrarás la salida a las ${draft.exitTime} y ${formatDeclaredMinutes(confirmationMinutes)} como horas declaradas. Una vez confirmada, la jornada quedará en solo lectura.`} confirmLabel="Sí, continuar" secondary="No, seguir editando" busy={busy} cancel={() => setView("close")} confirm={submitClose} /> : null}
    {view === "success" && successDate ? <Success date={successDate} close={() => { setSuccessDate(null); setView(null); }} /> : null}
  </>;
}

function Modal({ title, children, close }: { title: string; children: React.ReactNode; close: () => void }) { return <div aria-modal="true" className="fixed inset-0 z-50 flex items-center justify-center bg-black/35 p-4 backdrop-blur-[2px]" role="dialog"><section className="relative max-h-[92vh] w-full max-w-lg overflow-y-auto rounded-[22px] bg-white p-6 shadow-[0_28px_80px_rgba(15,23,42,0.25)] sm:p-8"><button aria-label="Cerrar" className="absolute top-4 right-4 p-2 text-[#697186]" onClick={close} type="button"><X /></button><h2 className="pr-10 text-2xl font-bold">{title}</h2>{children}</section></div>; }

function StartDialog({ clients, draft, today, historical, manual, calculatedHours, activities, error, change, updateActivity, addActivity, removeActivity, setManual, cancel, proceed }: { clients: Client[]; draft: Draft; today: string; historical: boolean; manual: boolean; calculatedHours: string; activities: HistoricalActivity[]; error: string | null; change: (value: Partial<Draft>) => void; updateActivity: (id: string, value: Partial<HistoricalActivity>) => void; addActivity: () => void; removeActivity: (id: string) => void; setManual: (value: boolean) => void; cancel: () => void; proceed: () => void }) {
  return <Modal close={cancel} title={historical ? "Registrar jornada anterior" : "Registrar ingreso"}><p className="mt-2 text-sm text-[#697186]">Selecciona la fecha de asistencia. Las fechas pasadas se registran completas y cerradas.</p><label className="mt-5 block text-sm font-semibold">Fecha de asistencia<input className="consultant-field mt-2" type="date" max={today} value={draft.workDate} onChange={(event) => { setManual(false); change({ workDate: event.target.value }); }} /></label><label className="mt-5 block text-sm font-semibold">Tipo de jornada<select className="consultant-field mt-2" value={draft.workType} onChange={(event) => change({ workType: event.target.value as Draft["workType"] })}><option value="" disabled>Selecciona un tipo</option><option value="remote">Remota</option><option value="onsite">Presencial</option></select></label><label className="mt-5 block text-sm font-semibold">Cliente asignado<select className="consultant-field mt-2" value={draft.clientId} onChange={(event) => change({ clientId: event.target.value })}>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label className="mt-5 block text-sm font-semibold">Hora de ingreso<input className="consultant-field mt-2" type="time" value={draft.entryTime} onChange={(event) => change({ entryTime: event.target.value })} /></label>{historical ? <HistoricalFields draft={draft} calculatedHours={calculatedHours} activities={activities} change={change} updateActivity={updateActivity} addActivity={addActivity} removeActivity={removeActivity} manual={manual} setManual={setManual} /> : null}{error ? <p className="mt-4 text-sm text-red-700">{error}</p> : null}<Buttons cancel={cancel} confirm={proceed} label="Continuar" /></Modal>;
}

function HistoricalFields({ draft, calculatedHours, activities, change, updateActivity, addActivity, removeActivity, manual, setManual }: { draft: Draft; calculatedHours: string; activities: HistoricalActivity[]; change: (value: Partial<Draft>) => void; updateActivity: (id: string, value: Partial<HistoricalActivity>) => void; addActivity: () => void; removeActivity: (id: string) => void; manual: boolean; setManual: (value: boolean) => void }) {
  return <div className="mt-5 border-t pt-5"><p className="text-sm font-semibold text-[#52617a]">Datos de la jornada anterior</p><label className="mt-4 block text-sm font-semibold">Hora de salida<input className="consultant-field mt-2" type="time" value={draft.exitTime} onChange={(event) => change({ exitTime: event.target.value })} /></label><label className="mt-5 block text-sm font-semibold">Horas trabajadas declaradas<input className="consultant-field mt-2" inputMode="numeric" placeholder="Completa ingreso y salida" value={manual ? draft.declaredHours : calculatedHours} onBlur={() => manual && change({ declaredHours: normalizeDeclaredHours(draft.declaredHours) })} onChange={(event) => { setManual(true); change({ declaredHours: event.target.value }); }} /></label><p className="mt-1 text-xs text-[#697186]">{manual ? "Formato HH:MM. Ejemplo: 6 se normaliza a 06:00." : "Calculadas automáticamente desde ingreso y salida. Puedes editar este campo si necesitas declarar otra cantidad."}</p>{manual ? <button className="mt-3 min-h-10 rounded-lg border border-[#a9c000] px-4 text-sm font-semibold text-[#617300]" onClick={() => setManual(false)} type="button">Usar cálculo automático</button> : null}<ActivitiesEditor activities={activities} updateActivity={updateActivity} addActivity={addActivity} removeActivity={removeActivity} /></div>;
}

function ActivitiesEditor({ activities, updateActivity, addActivity, removeActivity }: { activities: HistoricalActivity[]; updateActivity: (id: string, value: Partial<HistoricalActivity>) => void; addActivity: () => void; removeActivity: (id: string) => void }) {
  return <div className="mt-6 border-t pt-5"><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold text-[#52617a]">Actividades realizadas</p><button className="inline-flex min-h-10 items-center gap-1 rounded-lg border border-[#a9c000] px-3 text-sm font-semibold text-[#617300]" onClick={addActivity} type="button"><Plus className="size-4" />Agregar actividad</button></div><p className="mt-1 text-xs text-[#697186]">Registra una o varias actividades, cada una con su propio motivo.</p><div className="mt-4 space-y-4">{activities.map((activity, index) => <div className="rounded-xl border border-[#e3e7ec] bg-[#fafbfc] p-4" key={activity.id}><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold">Actividad {index + 1}</p>{activities.length > 1 ? <button aria-label={`Eliminar actividad ${index + 1}`} className="rounded-lg p-2 text-red-600 hover:bg-red-50" onClick={() => removeActivity(activity.id)} type="button"><Trash2 className="size-4" /></button> : null}</div><label className="mt-3 block text-sm font-semibold">Área<select className="consultant-field mt-2" value={activity.areaCode} onChange={(event) => updateActivity(activity.id, { areaCode: event.target.value, otherAreaName: event.target.value === "other" ? activity.otherAreaName : "" })}><option value="" disabled>Selecciona un área</option>{ATTENDANCE_AREAS.map((area) => <option key={area.code} value={area.code}>{area.label}</option>)}</select></label>{activity.areaCode === "other" ? <label className="mt-4 block text-sm font-semibold">Área específica<input className="consultant-field mt-2" maxLength={120} value={activity.otherAreaName} onChange={(event) => updateActivity(activity.id, { otherAreaName: event.target.value })} /></label> : null}<label className="mt-4 block text-sm font-semibold">Motivo o concepto de la reunión<textarea className="consultant-field mt-2 min-h-24" maxLength={250} value={activity.description} onChange={(event) => updateActivity(activity.id, { description: event.target.value })} /></label></div>)}</div></div>;
}

function ActivityDialog({ activity, busy, error, cancel, submit }: { activity: Activity | null; busy: boolean; error: string | null; cancel: () => void; submit: (data: FormData) => void }) { const [area, setArea] = useState(activity?.areaCode ?? ""); return <Modal close={cancel} title={activity ? "Editar actividad" : "Registrar actividad"}><form action={submit} className="mt-6"><label className="block text-sm font-semibold">Área<select className="consultant-field mt-2" name="areaCode" required value={area} onChange={(event) => setArea(event.target.value)}><option value="" disabled>Selecciona un área</option>{ATTENDANCE_AREAS.map((item) => <option key={item.code} value={item.code}>{item.label}</option>)}</select></label>{area === "other" ? <label className="mt-5 block text-sm font-semibold">Área específica<input className="consultant-field mt-2" defaultValue={activity?.otherAreaName ?? ""} name="otherAreaName" required /></label> : null}<label className="mt-5 block text-sm font-semibold">Motivo o concepto de la reunión<textarea className="consultant-field mt-2 min-h-28" defaultValue={activity?.description ?? ""} name="description" required /></label>{error ? <p className="mt-4 text-sm text-red-700">{error}</p> : null}<Buttons cancel={cancel} busy={busy} label="Guardar actividad" /></form></Modal>; }

function CloseDialog({ draft, calculatedHours, manual, setManual, error, activityCount, change, cancel, proceed }: { draft: Draft; calculatedHours: string; manual: boolean; setManual: (value: boolean) => void; error: string | null; activityCount: number; change: (value: Partial<Draft>) => void; cancel: () => void; proceed: () => void }) { return <Modal close={cancel} title="Registrar salida"><p className="mt-2 text-sm text-[#697186]">Confirma la salida. Las horas se calculan automáticamente desde tu ingreso, aunque puedes corregirlas si la jornada efectiva fue diferente.</p><label className="mt-5 block text-sm font-semibold">Hora de salida<input className="consultant-field mt-2" type="time" value={draft.exitTime} onChange={(event) => change({ exitTime: event.target.value })} /></label><label className="mt-5 block text-sm font-semibold">Horas trabajadas declaradas<input className="consultant-field mt-2" inputMode="numeric" placeholder="Completa la hora de salida" value={manual ? draft.declaredHours : calculatedHours} onBlur={() => manual && change({ declaredHours: normalizeDeclaredHours(draft.declaredHours) })} onChange={(event) => { setManual(true); change({ declaredHours: event.target.value }); }} /></label><p className="mt-1 text-xs text-[#697186]">{manual ? "Formato HH:MM. Ejemplo: 6 se normaliza a 06:00." : "Esta cantidad se calculó automáticamente desde tu hora de ingreso y salida. Puedes editarla si necesitas declarar menos o más horas."}</p>{manual ? <button className="mt-3 min-h-10 rounded-lg border border-[#a9c000] px-4 text-sm font-semibold text-[#617300]" onClick={() => setManual(false)} type="button">Usar cálculo automático</button> : null}{activityCount === 0 ? <p className="mt-4 text-sm text-red-700">Debes registrar al menos una actividad antes de cerrar.</p> : null}{error ? <p className="mt-4 text-sm text-red-700">{error}</p> : null}<Buttons cancel={cancel} confirm={proceed} label="Marcar asistencia" /></Modal>; }

function Confirm({ title, description, confirmLabel, secondary = "Cancelar", busy, cancel, confirm }: { title: string; description: string; confirmLabel: string; secondary?: string; busy: boolean; cancel: () => void; confirm: () => void }) { return <Modal close={cancel} title={title}><div className="mt-5 flex gap-3 rounded-2xl bg-[#f4f7e9] p-4"><MapPin className="size-5 text-[#6c8500]" /><p className="text-sm text-[#394458]">{description}</p></div><p className="mt-4 text-sm text-[#697186]">La ubicación se solicitará ahora; si no está disponible, el registro continuará con la incidencia correspondiente.</p><Buttons cancel={cancel} confirm={confirm} busy={busy} cancelLabel={secondary} label={confirmLabel} /></Modal>; }
function Success({ date, close }: { date: string; close: () => void }) { return <Modal close={close} title="Asistencia marcada"><div className="mt-6 text-center"><CheckCircle2 className="mx-auto size-16 text-[#758f00]" /><p className="mt-5 text-lg font-semibold">Tu asistencia del {formatLimaDate(date)} fue marcada correctamente.</p><p className="mt-2 text-[#697186]">Gracias por registrar tu jornada.</p><button className="mt-7 min-h-11 rounded-xl bg-[#afc500] px-7 font-semibold text-white" onClick={close}>Entendido</button></div></Modal>; }
function Buttons({ cancel, confirm, label, busy = false, cancelLabel = "Cancelar" }: { cancel: () => void; confirm?: () => void; label: string; busy?: boolean; cancelLabel?: string }) { return <div className="mt-7 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button className="min-h-11 rounded-xl border border-[#d7dce4] px-5 font-semibold" disabled={busy} onClick={cancel} type="button">{cancelLabel}</button>{confirm ? <button className="min-h-11 rounded-xl bg-[#a9c000] px-5 font-semibold text-white disabled:opacity-60" disabled={busy} onClick={confirm} type="button">{busy ? "Guardando…" : label}</button> : <button className="min-h-11 rounded-xl bg-[#a9c000] px-5 font-semibold text-white disabled:opacity-60" disabled={busy} type="submit">{busy ? "Guardando…" : label}</button>}</div>; }

function OpenCard({ attendance, pending, busy, error, onActivity, onEdit, onDelete, onClose }: { attendance: OpenAttendance; pending: boolean; busy: boolean; error: string | null; onActivity: () => void; onEdit: (activity: Activity) => void; onDelete: (activity: Activity) => void; onClose: () => void }) { return <div className="w-full xl:w-[500px]">{pending ? <div className="mb-3 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-medium text-red-800">Tienes una jornada pendiente del {formatLimaDate(attendance.workDate)}. Debes marcar su salida antes de iniciar una nueva.</div> : null}<div className="rounded-[18px] border border-[#e8ebef] bg-white p-5 shadow-[0_12px_35px_rgba(15,23,42,0.06)]"><p className="text-sm font-semibold text-[#68758b]">Jornada abierta · {attendance.clientName}</p><p className="mt-1 text-xl font-bold">Ingreso: {attendance.entryTime}</p><div className="mt-4 space-y-2">{attendance.activities.map((activity) => <div className="flex items-start justify-between gap-3 rounded-xl bg-[#f7f8fa] px-3 py-2" key={activity.id}><p className="text-sm"><strong>{activity.areaCode === "other" ? activity.otherAreaName : getAttendanceAreaLabel(activity.areaCode)}:</strong> {activity.description}</p><span className="flex"><button aria-label="Editar actividad" onClick={() => onEdit(activity)} type="button"><Pencil className="size-4" /></button><button aria-label="Eliminar actividad" disabled={busy} className="ml-2 text-red-600" onClick={() => onDelete(activity)} type="button"><Trash2 className="size-4" /></button></span></div>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-2"><button className="min-h-11 rounded-xl border border-[#cfd6df] px-4 font-semibold" onClick={onActivity} type="button"><Plus className="mr-1 inline size-4" />Actividad</button><button className="min-h-11 rounded-xl bg-[#afc500] px-4 font-semibold text-white disabled:opacity-60" disabled={busy || !attendance.activities.length} onClick={onClose} type="button">Registrar salida</button></div>{!attendance.activities.length ? <p className="mt-3 text-xs text-[#697186]">Registra al menos una actividad para habilitar la salida.</p> : null}{error ? <p className="mt-3 text-sm text-red-700">{error}</p> : null}</div></div>; }
