"use client";

import { Eye, EyeOff, Pencil, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";

import { updateConsultantAccount } from "@/app/(admin)/admin/consultants/actions";
import { PhotoEditor, cropAvatar } from "@/components/admin/new-consultant-dialog";
import type { ConsultantRecord } from "@/lib/admin/consultants";

type Point = { x: number; y: number };
type Size = { width: number; height: number };

export function EditConsultantDialog({ consultant, clientNames }: { consultant: ConsultantRecord; clientNames: string[] }) {
  const router = useRouter();
  const [open, setOpen] = useState(false); const [showPassword, setShowPassword] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const [source, setSource] = useState<string | null>(null); const [size, setSize] = useState<Size | null>(null); const [zoom, setZoom] = useState(1); const [offset, setOffset] = useState<Point>({ x: 0, y: 0 });
  const [values, setValues] = useState({ fullName: consultant.fullName, dni: consultant.dni ?? "", phoneNumber: consultant.phoneNumber ?? "", username: consultant.username, password: "", clientName: consultant.clients[0]?.name ?? "" });
  function clamp(point: Point, nextZoom = zoom) { if (!size) return { x: 0, y: 0 }; const scale = Math.max(240 / size.width, 240 / size.height) * nextZoom; const maxX = Math.max(0, (size.width * scale - 240) / 2); const maxY = Math.max(0, (size.height * scale - 240) / 2); return { x: Math.min(maxX, Math.max(-maxX, point.x)), y: Math.min(maxY, Math.max(-maxY, point.y)) }; }
  async function save() { setBusy(true); setError(null); try { const form = new FormData(); form.set("userId", consultant.userId); Object.entries(values).forEach(([key, value]) => form.set(key, value)); if (source) form.set("avatar", await cropAvatar(source, zoom, offset)); const result = await updateConsultantAccount(form); if (!result.success) { setError(result.error); return; } setOpen(false); router.refresh(); } catch { setError("No fue posible actualizar el consultor."); } finally { setBusy(false); } }
  const field = (label: string, key: keyof typeof values, type = "text") => <label className="block text-sm font-semibold">{label}<input className="admin-field mt-2" inputMode={key === "dni" || key === "phoneNumber" ? "numeric" : undefined} maxLength={key === "dni" ? 8 : key === "phoneNumber" ? 9 : undefined} type={type} value={values[key]} onChange={(event) => setValues({ ...values, [key]: event.target.value })} /></label>;
  return <><button className="flex min-h-12 items-center gap-2 rounded-xl border border-[#cfd6df] bg-white px-5 font-semibold text-[#344056]" onClick={() => setOpen(true)} type="button"><Pencil className="size-5" />Editar consultor</button>{open ? <div aria-modal="true" className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-black/40 p-4 py-8" role="dialog"><section className="relative w-full max-w-4xl rounded-[24px] bg-white p-6 shadow-2xl sm:p-9"><button aria-label="Cerrar" className="absolute top-5 right-5 rounded-full p-2 hover:bg-[#f3f5f7]" onClick={() => !busy && setOpen(false)} type="button"><X /></button><h2 className="pr-10 text-3xl font-bold">Editar consultor</h2><p className="mt-2 text-[#697186]">La contraseña es opcional: déjala vacía para conservar la actual.</p><div className="mt-7 grid gap-8 lg:grid-cols-[1fr_280px]"><div className="grid content-start gap-5 sm:grid-cols-2">{field("Nombre completo", "fullName")} {field("Nro. de DNI", "dni")} {field("Nro. de celular", "phoneNumber")} {field("Nombre de usuario", "username")}<label className="relative block text-sm font-semibold">Nueva contraseña opcional<input autoComplete="new-password" className="admin-field mt-2 pr-12" type={showPassword ? "text" : "password"} value={values.password} onChange={(event) => setValues({ ...values, password: event.target.value })} /><button aria-label={showPassword ? "Ocultar contraseña" : "Mostrar contraseña"} className="absolute right-1 bottom-1 rounded p-3 text-[#697186]" onClick={() => setShowPassword(!showPassword)} type="button">{showPassword ? <EyeOff className="size-5" /> : <Eye className="size-5" />}</button></label><label className="block text-sm font-semibold">Cliente asignado<input className="admin-field mt-2" list="edit-client-names" value={values.clientName} onChange={(event) => setValues({ ...values, clientName: event.target.value })} /><datalist id="edit-client-names">{clientNames.map((name) => <option key={name} value={name} />)}</datalist></label>{error ? <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700 sm:col-span-2">{error}</p> : null}<div className="flex flex-col-reverse gap-3 pt-2 sm:col-span-2 sm:flex-row sm:justify-end"><button className="min-h-12 rounded-xl border border-[#d7dce4] px-6 font-semibold" onClick={() => setOpen(false)} type="button">Cancelar</button><button className="min-h-12 rounded-xl bg-[#afc500] px-7 font-semibold text-white disabled:opacity-60" disabled={busy} onClick={save} type="button">{busy ? "Guardando..." : "Guardar cambios"}</button></div></div><div><p className="mb-2 text-sm font-semibold">Foto de perfil</p><PhotoEditor clampOffset={clamp} offset={offset} onError={setError} onImageSizeChange={setSize} onOffsetChange={setOffset} onSourceChange={setSource} onZoomChange={setZoom} photoSource={source} zoom={zoom} /></div></div></section></div> : null}</>;
}
